export const INIT_LOGIN_FUNCTION = 'INIT_LOGIN_FUNCTION';
export const BEGIN_POST_LOGIN = 'BEGIN_POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';